### ISSUE TITLE
IHM. Mise a jour du panier

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#1]
On ajoute un produit au panier
On visualise le panier
On augmente le nombre de produits en appuyant sur le "+"
La valeur du panier affichée à droite ne se met pas à jour. Un rafraichissement de l'écran effectue la mise à jour.

**Comment by rmvonji** [comment]
Il se met à jour mais au bout de 2/3 secondes. Il faudrait peut être afficher un spinner le temps du rafraichissement.

**Comment by ochaillat** [comment]
Pour les sources je t’ai pas envoyé les bonnes. Grrr 👿

**Comment by ochaillat** [comment]
En effet un "spinner" serait bien
