### ISSUE TITLE
ID 14 dans backlog Excel Pouvoir gerer mon panier

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#10]
En tant que client, je souhaite gerer mon panier (ajouter et supprimer des produits)

**Comment by rmvonji** [comment]
C'est un bug ou un élément du backlog?

**Comment by ochaillat** [comment]
meme reponse que précédemment. C'est une issue qui est dans la colonne Done. 

Olivier 



De: "rmvonji" <notifications@github.com> 
À: "ochaillat/soaggyshopIssuesAndEnhancements" <soaggyshopIssuesAndEnhancements@noreply.github.com> 
Cc: "olivier" <olivier.chaillat@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 1 Octobre 2020 18:35:47 
Objet: Re: [ochaillat/soaggyshopIssuesAndEnhancements] ID 14 dans backlog Excel Pouvoir gerer mon panier (#10) 





C'est un bug ou un élément du backlog?
