### ISSUE TITLE
Livraison gratuite au dessus d'une certaine somme.

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#12]
J'ai l'impression que tu as pris 75€ comme le prix de la livraison alors que c'est le montant du panier au dessus duquel la livraison est gratuite. Voir Issue 11 pour le prix de la livraison

**Comment by rmvonji** [comment]
Dans la prochaine version, le frais de livraison sera configurable dans le backend

**Comment by rmvonji** [comment]
oui, ça sera configurable dans la prochaine version

**Comment by rmvonji** [comment]
Tu peux configurer le coût de la livraison dans l'admin
