### ISSUE TITLE
Livraison disparait sur la confirmation

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#14]
Le prix de la  livraison n'apparait pas sur le 4e ecran

![fraisDeLivraisonEtape4nAffichePasLaLivraison](https://user-images.githubusercontent.com/63843460/95600485-85018f00-0a52-11eb-9a17-73cd30c96421.jpg)

**Comment by rmvonji** [comment]
ok
