### ISSUE TITLE
Processus de validation. 3e ecran "paiement" est inutile à priori

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#15]
Comme on est en BtoB le paiement s'effectue à reception de facture. 

![fraisDeLivraisonSansMinimumDeCde_etape3](https://user-images.githubusercontent.com/63843460/95601690-1a515300-0a54-11eb-88d2-c7ef22137bb8.jpg)

**Comment by rmvonji** [comment]
iI faudrait peut être l'appeler autrement mais il bien utile avant de confirmer la commande.

cet écran permet d'éviter beaucoup d'erreurs de commandes  de la part des client que l'admin devra annuler et recommander.

**Comment by ochaillat** [comment]
Faudrait peut-être rajouter l'option "Paiement à réception de facture"

**Comment by ochaillat** [comment]
Ah. Je suppose que c'est l'option "Contractuel" qui veut dire paiement par facture. On verra avec Alex ce qui conviendrait.

**Comment by rmvonji** [comment]
C'est ça.

Il faudrait le rendre configurable et dans le but de le cacher pour l'atelier des lilas
