### ISSUE TITLE
Admin. colonnes par ordre alphabetique

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#16]
Sur l'ecran Members la 1ere colonne n'est pas "clickable" pour la mettre en ordre alphabetique.

**Comment by rmvonji** [comment]
Le tri n'est pas à l'ordre du jour.

Par contre la recherche par nom serait bien.

La recherche des membres se fait aujourd'hui par email mais vu qu'on a mis des chiffres à la place des mails, bé, le resultat n'est pas top

**Comment by ochaillat** [comment]
Je crois que j'ai nu code de tri en javascript qque part. Je peux le chercher si tu veux.

**Comment by ochaillat** [comment]
En fait tu sembles avoir résolu le problème. Bravo
