### ISSUE TITLE
Admin: Recherche dans Members

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#17]
Le champ recherche n'a pas d'icone indiquant sa destination. si j'entre ess ou meme la lettre e je n'obtiens aucun résultat

**Comment by ochaillat** [comment]
Le fait que google m'a mis en mode "anglais" ne semble pas avoir aidé. Par contre en mode" francais" j en'arrive pas à trouver essaiAppClient en tapant "ess"

**Comment by rmvonji** [comment]
Tu veux dire que tu n'arrives pas trouvé certains clients par leurs nom?

**Comment by ochaillat** [comment]
Oui. C est ça

**Comment by ochaillat** [comment]
Je t'ai envoyé une invitation. Dis moi si tu l'as recu. ok ? 

Olivier 



De: "rmvonji" <notifications@github.com> 
À: "ochaillat" <soaggyshopIssuesAndEnhancements@noreply.github.com> 
Cc: "olivier" <olivier.chaillat@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 14 Octobre 2020 12:37:36 
Objet: Re: [ochaillat/soaggyshopIssuesAndEnhancements] Admin: Recherche dans Members (#17) 





Tu veux dire que tu n'arrives pas trouvé certains clients par leurs nom?

**Comment by ochaillat** [comment]
Oui c ce que je veux dire. 
Sinon je t'ai envoyé une "invitation". Je sais pas si elle te permettra d'accéder à l'onglet projet.
Dans l'onglet projet il faut cliquer sur "bugs et requêtes" qui est le nom du projet.

**Comment by ochaillat** [comment]
Il n'y a toujours pas d'icone de recherche "loupe" mais je vais qd meme mettre dans les resolus parce que la recherche marche
