### ISSUE TITLE
heure date ecran final erronée

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#2]
Une fois que la commande est validée l'heure qui s'affiche semble être l'heure GMT. Voir piece jointe. 
![heureDateErronee](https://user-images.githubusercontent.com/63843460/94250361-6ca55680-ff21-11ea-9986-d1e88721325f.jpg)

**Comment by rmvonji** [comment]
Ok je corrige

**Comment by ochaillat** [comment]
L'heure d'hiver n'a pas été prise en compte
