### ISSUE TITLE
Produits clients spécifiques

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#20]
Foodles,LSG, Epicerie... sont des clients qui ont des produits spécifiques qui (je suppose) leur sont dédiés. Il faudra voir avec Alexandra comment on les gère.

**Comment by rmvonji** [comment]
Good morning:
Cake Chocolat et Pépites - 350g tranché GOOD MORNING
Cake Citron Pavot - 350g tranché GOOD MORNING
  Duo de cake x2 - GOOD MORNING 
  Duo de Muffin x12 - GOOD MORNING 
  Fromage blanc, miel et granola x5 - GOOD MORNING  





pop chef:

  Compote et crumble Pop Chef 
  Compote et granola Pop Chef
Compote pomme fruit rouge et crumble pavot Pop Chef 
Crémeux citron et granola POP CHEF
Crémeux et crumble POP CHEF
  Fromage blanc, coulis et granola - POP CHEF 
  Fromage blanc, crème de marron et granola - POP CHEF 
 Fromage blanc, miel et granola - POP CHEF 
  Fromage blanc, morceaux fruits rouge et granola - POP CEHF  



Monoprix:

  Quiche brocoli/cheddar/muscade - 12cm monoprix  
  Quiche butternut/ricotta/compotée tomate/graine courge - 12cm monoprix 
  Quiche courgette/mozza/compotée tomate - 12cm monoprix  
  Quiche epinard/chèvre/romarin - 12cm monoprix 

Quiche lardon/raclette/oignon/muscade - 12cm monoprix
  Quiche oignon confit - 12cm monoprix 
  Quiche lorraine - 12cm monoprix 
  Quiche poireau/bacon/muscade - 12cm monoprix  

Quiche poireau/bleu/muscade - 12cm monoprix  

Quiche poireau/bacon/muscade - 12cm monoprix

 

Campanile:
  Quiche petit pois/féta/oignon - 12cm Campanile

**Comment by ochaillat** [comment]
Plus Foodles et LSG

**Comment by ochaillat** [comment]
En fait il faut éliminer les produits dont le nom se terminent par 
Campanile
monoprix
POP CHEF
GOOD MORNING
Foodles
epicerie
et LSG
Je peux le faire dans le connecteur ASCM/Sellsy

**Comment by ochaillat** [comment]
Je vois encore Foodles et Epicerie dans les choix du menu "Conventionnels"
