### ISSUE TITLE
Adresse de livraison non modifiable

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#21]
Lors de la commande à l'etape 2 "Informations" les adresses ne doivent pas être modifiables. Ces adresses devraient être modifiables dans le futur  dans la fenêtre "mon compte". On pourrait ainsi rajouter l'information à l'étape 2 comme quoi si le client veut changer une des adresses il faut "version alpha" qu'il contacte ASCM, "version 1" qu'il aille dans "mon compte"

**Comment by rmvonji** [comment]
Il faut dans ce cas s'assurer que sellsy renvoie des adresses valide, car je ne peux pas créer une commande si il me manque un champs dans un formulaire.

Le fait de laisser les adresses modifiables c'est juste pour ne pas bloquer la commande au cas ou on a importer une addesse invalide.

Perso, ça ne me derange pas que ça soit modifiable.

**Comment by ochaillat** [comment]
OK ben on va laisser comme ca pour l'instant mais peux tu rajouter "France" par défault pour le pays ?
