### ISSUE TITLE
nom Client dans ecran Panier

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#23]
Le nom du client qui apparaissait dans l'ecran d'accueil n'apparait pas dans l'ecran qui affiche le panier

![23nomClientEcranPanier](https://user-images.githubusercontent.com/63843460/96882239-6605f280-147f-11eb-9a0d-ecaae93ea2be.jpg)

**Comment by rmvonji** [comment]
Le nom a été supprimé dans l'écran d'accueil.
Il ne sert à rien à cet endroit et pourrait prendre bcp de place en fonction des clients du coup ça casse le layout.

Il est affiché totalement dans la page des paniers où il ya plus de place.

Il faudrait dans la page d'accueil envisage de rajouter un popup qui afficher le nom complet du client au survol de l'icone
