### ISSUE TITLE
produit sans nom

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#24]
En Bio ou conventionnel le p^remier produit à 14,3 n'a pas de nom qui s'affiche

**Comment by ochaillat** [comment]
![24produitSansNom](https://user-images.githubusercontent.com/63843460/96884540-e62d5780-1481-11eb-9296-c4f4c50ee472.jpg)

**Comment by rmvonji** [comment]
Corrigé, mais dis moi si tu vois d'autres endroits où il est vide encore
