### ISSUE TITLE
bouton "aller au panier" sans effet

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#3]
Quand on selectionne un produit l'option "aller au panier" de l'ecran qui s'affiche ne donne rien. Seul l'option "continuer a un effet et permet de revenir au choix des produits. Par contre le panier est bien mis à jour.
![allerAuPanierBloque](https://user-images.githubusercontent.com/63843460/94281820-63cb7980-ff4f-11ea-889f-84f3766b41e6.jpg)

**Comment by rmvonji** [comment]
Ok je regarde ça

**Comment by ochaillat** [comment]
Comment se fait-il que je ne peux pas t'assigner des issues ?
