### ISSUE TITLE
Catalogue - Affichage persistant

### ISSUE THREAD

**Issue by CelineAdl** [ochaillat/soaggyshopIssuesAndEnhancements#32]
Quand je suis dans le catalogue convo et que je clique sur une sous catégorie ex quiches, la fenêtre du catalogue ne disparait pas pour laisser place aux produits

![Capture d’écran (9)](https://user-images.githubusercontent.com/77993229/105761944-0888b280-5f54-11eb-9156-f578281f4af7.png)

**Comment by rmvonji** [comment]
Ce comportement va être changé à la prochaine livraison.

Il y aura une fenêtre pour tous les catalogues
