### ISSUE TITLE
Calcul du panier

### ISSUE THREAD

**Issue by CelineAdl** [ochaillat/soaggyshopIssuesAndEnhancements#34]
Le calcul du panier est faux

![Capture d’écran (11)](https://user-images.githubusercontent.com/77993229/105763330-f4de4b80-5f55-11eb-8f8f-78b76656a6b8.png)

**Comment by rmvonji** [comment]
Peux tu me dire ce qui est faux? le CNC, les -10% ou quel calcul?

En mode livraison standard ou les deux?

**Comment by CelineAdl** [comment]
Le panier + les frais de livraison + la tva = 80,79€ et non 90,82€
