### ISSUE TITLE
Erreur au moment de la validation du panier

### ISSUE THREAD

**Issue by CelineAdl** [ochaillat/soaggyshopIssuesAndEnhancements#35]
En livraison standard, une fois l'adresse renseignée la commande n'est pas prise en compte, je reçois un message d'erreur

 
![Capture d’écran (12)](https://user-images.githubusercontent.com/77993229/105763774-6ddda300-5f56-11eb-8430-2dac4307184c.png)

**Comment by rmvonji** [comment]
Ok je vais tester
