### ISSUE TITLE
Bouton Reproduire commande

### ISSUE THREAD

**Issue by CelineAdl** [ochaillat/soaggyshopIssuesAndEnhancements#37]
Après une commande passée, le panier ne se vide pas automatiquement, il reste encore les 5 produits commandés dans le panier, un message d'erreur apparait.
Quand je reclic sur l'icone panier, j'arrive sur un panier et je peux ensuite reproduire la commande.

![Capture d’écran (15)](https://user-images.githubusercontent.com/77993229/105764606-77b3d600-5f57-11eb-9944-76e1b40c2a28.png)

**Comment by rmvonji** [comment]
J'ai vu cela, il y a une régression sur la fonctionnalité
