### ISSUE TITLE
Calcul TVA incorrect

### ISSUE THREAD

**Issue by CelineAdl** [ochaillat/soaggyshopIssuesAndEnhancements#38]
Il faudrait paramétrer la TVA à 5.50% pour les produits et 20% pour les frais de livraison
La TVA est disponible pour chaque produit dans sellsy

![Capture d’écran (16)](https://user-images.githubusercontent.com/77993229/105765156-4556a880-5f58-11eb-8b9b-80670f68c4fa.png)

**Comment by rmvonji** [comment]
Ok
