### ISSUE TITLE
Mail de confirmation de commande

### ISSUE THREAD

**Issue by CelineAdl** [ochaillat/soaggyshopIssuesAndEnhancements#39]
Nous recevons bien un mail de commande client click and collect mais le mail ne contient pas de lien proposant la fonction confirmation de command. De plus elle est déjà au statut confirmée chez le client.

Aussi je ne trouve pas le BL dans Sellsy.

![Capture d’écran (18)](https://user-images.githubusercontent.com/77993229/105765963-6ff53100-5f59-11eb-9d5e-bfd3fd1c1cab.png)

![Capture d’écran (19)](https://user-images.githubusercontent.com/77993229/105766190-b9458080-5f59-11eb-99f6-c268b4dfbf4e.png)

**Comment by rmvonji** [comment]
Tu veux quand même valide la commande CNC? Même si le client a déjà payé.

Sinon il a une règle qui gère cela dans l'admin.

Je peux désactiver la règle du coup les commandes CNC seront à confirmer

**Comment by CelineAdl** [comment]
Non désolée tu as raison, pas de confirmation pour le cliclk and collect, c'est juste que comme on ne m'a pas proposé de paiement j'ai cru un instant que c'était du standard.
