### ISSUE TITLE
livraison a domicile Gratuit

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#4]
La livraison a domicile ne devrait pas être gratuite en dessous de 75 euros sauf cas particulier. Donc la livraison devrait être facturée et affichée

**Comment by rmvonji** [comment]
C'est quoi la règle sur la livraison?

Est ce qu'il y a des exceptions par client?

**Comment by ochaillat** [comment]
La regle c'est les 75 euros mais je pense qu'il y a des exceptions.  Pour l'instant utilise cette regle si c'est possible.

**Comment by rmvonji** [comment]
Le coût de la livraison est maintenant configurable
