### ISSUE TITLE
Récupération mot de passe 

### ISSUE THREAD

**Issue by CelineAdl** [ochaillat/soaggyshopIssuesAndEnhancements#40]
Ma demande de renouvellement de mot de passe n'a pas aboutit, je n'ai pas reçu de mail

![Capture d’écran (20)](https://user-images.githubusercontent.com/77993229/105768086-29ed9c80-5f5c-11eb-8ce2-c3f27c615fce.png)

**Comment by CelineAdl** [comment]
Mail reçu dans mes spams, par contre il y a des erreurs d'affichage pour les caractères accentués.

Quand je clique dans le corps du mail sur : "veuillez suivre ce lien etc." ça me renvoie à la page de connexion

**Comment by rmvonji** [comment]
Je vais créer un bug pour le lien qui ne renvoie pas dans la récupération de MPD.

Par contre je n'ai pas de problème de problème d'encodage en testant. Est-ce que c'est lié au navigateur?

Il faudrait que je demande à Olivier de tester pour voir si il des problèmes d'encodage

**Comment by ochaillat** [comment]
J'ai essayé cette fonctionnalité avec essaiAppClient sans succès
![image](https://user-images.githubusercontent.com/63843460/107619340-50e1e900-6c53-11eb-9547-5fbd855d82e7.png)

Je n'ai pas reçu de mail à olivier.chaillat@free.fr
