### ISSUE TITLE
new member creation

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#7]
J'ai créé un nouveau "member" mais quand j'essaie de l'utiliser pour soaggyshop ça ne marche pas

![listMembers](https://user-images.githubusercontent.com/63843460/94701644-2a26b400-033d-11eb-8190-4d13a5012cb6.jpg)

![newUserDoesNotWork](https://user-images.githubusercontent.com/63843460/94701214-aa98e500-033c-11eb-9af8-49757122fb54.jpg)

**Comment by rmvonji** [comment]
C'est toujours d'actualité?

**Comment by ochaillat** [comment]
Non c'etait avant que tu mettes les clients dans les members
