### ISSUE TITLE
ID 1 dans backlog excel "Pouvoir créer un compte client" Quand on cree un nouveau membre on ne se voit pas proposé la liste selectable des clients

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#8]
![newMemberSansListeClients](https://user-images.githubusercontent.com/63843460/94702238-d10b5000-033d-11eb-9811-3a77086e437e.jpg)

**Comment by rmvonji** [comment]
Je ne comprend pas le problème

**Comment by ochaillat** [comment]
L'administrateur doit pouvoir créer un nouvel utilisateur "client" non ? et dans ce cas il faudrait lui afficher la liste des clients quand il veut créer un nouveau "member"
