### ISSUE TITLE
ID 13 dans backlog Excel Pouvoir commander des produits

### ISSUE THREAD

**Issue by ochaillat** [ochaillat/soaggyshopIssuesAndEnhancements#9]
En tant que client souhaite naviguer dans les sous familles 
En tant que client, je souhaite commander des produits depuis le catalogue

**Comment by rmvonji** [comment]
Quel est le bug?

**Comment by ochaillat** [comment]
Il n'y a pas de bug. J'ai mis qques lignes du backlog excel qui sont résolues. Si tu ergardes le "projeté tu verras que "l'issue" est dans la colonne done
